services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fiuba_mentor
    volumes:
      - ./.volumes/postgres/data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"